---
title-block-banner-color: "#151550ff"
---

# Lista de pares revisores {.unnumbered}

**Roberto Ariel Abeldaño** | Universidad de la Sierra Sur y CONACYT, México

**Ana Beatriz Acevedo Jaramillo** | Departamento de Ingeniería Civil, Universidad EAFIT, Medellín, Colombia

**Melissa Acosta | **Universidad de la Costa, Barranquilla, Colombia

**Franck A. Audemard M.** |Escuela de Geología, Minas y Geofísica, Universidad Central de Venezuela

**Edier Aristizábal** | Departamento de Geociencias y Medio Ambiente, Universidad Nacional de Colombia, Sede Medellín

**Álvaro Ávila-Díaz** | Department of Agricultural Engineering, Universidade Federal de Viçosa, Brasil

**José Emilio Baró Suárez** | Facultad de Geografía, Universidad Autónoma del Estado de México, México 

**Gustavo Barrantes** | Escuela de Ciencias Geográficas, Universidad Nacional, Costa Rica 

**Huáscar Bolívar Vallejo** | Universidad Mayor de San Simón, Bolivia

**Mireille Escudero** | Instituto de Ingeniería, Universidad Nacional de México, Ciudad de México, México

**María Adelaida Farah** | Facultad de Estudios Ambientales y Rurales, Pontificia Universidad Javeriana, Colombia

**Silvia E. Fontana** | Universidad Católica de Córdoba, Argentina

**Jorge Pedro Galve** | Departamento de Geodinámica, Universidad de Granada, España

**Helbert García-Delgado** | Servicio Geológico Colombiano, Grupo de evaluación de amenazas por movimientos en masa, Colombia

**Victor Manuel García Lemus** | Presidente de la Red Universitaria de las Américas y el Cribe para la RRD 

**Miguel Ángel Imaz** |	Universidad Autónoma de Baja California Sur, México

**Miguel Ángel Jaimes ****Téllez ** | Instituto de Ingeniería, UNAM, México

**Santiago Henao Villegas** |Facultad de Medicina Veterinaria y Zootecnia, Escuela de Graduados, Universidad CES, Medellín, Colombia

**David Ortega-Gaucin** | Instituto Mexicano de Tecnología del Agua, México

**Juan Diego Jaramillo Fernández** | Departamento de Ingeniería Civil, Universidad EAFIT, Medellín, Colombia

**Andrés León Prieto **| Universidad del Bosque - Escuela Colombiana de Medicina, Colombia

**Ana Lucía Maldonado** | Instituto de Investigaciones en Educación, Universidad Veracruzana, Xalapa, México

**Roberto J. Marín** | Facultad de Ingeniería, Universidad de Antioquia, Medellín, Colombia

**Hazel Marsh** | University of East Anglia, Reino Unido

**Mónica Elizabeth Mejía Escalante** | Escuela del Hábitat, Facultad de Arquitectura, Universidad Nacional de Colombia, Sede Medellín

**Ricardo J. Molares B.** | Perito oceanógrafo – DIMAR – CP3, Colombia

**Erick Cajigal Molina** | Universidad Autónoma del Carmen, México

**Claudia Montero-Liberona** | Facultad de Comunicaciones, Pontificia Universidad Católica de Chile, Chile 

**Nelson Obregón** | Instituto Javeriano del Agua, Pontificia Universidad Javeriana, Colombia

**Juan Andrés Oviedo Amézquita** | FC Control y Diseño de Estructuras SAS, Colombia

**Aceneth Perafán Cabrera** | Departamento de Historia, Universidad del Valle, Colombia 

**Rogelio Pineda Murillo** | Consultor, Planificación Territorial, Desarrollo Sostenible y Medio Ambiente, Geografía y Cambio Climático, Colombia

**Carlos E. Reinoza** | CICESE - Centro de Investigación Científica y de Educación Superior de Ensenada, Baja California, México

**Eduardo Reinoso** |Instituto de Ingeniería, UNAM, México

**Miguel Enrique Sarmiento** | Dirección de Gestión del Ordenamiento Ambiental y Territorial, CAR de Cundinamarca, Colombia

**Juan Sebastián de Plaza Solórzano** | Universidad Católica de Colombia

**Olga Patricia Quintero García** | Corpocaldas, Manizales, Colombia

**Vladimir G. Toro** | Facultad de Ingeniería, Universidad de Antioquia, Medellín, Colombia

**Mauricio A. Torres Méndez **| Universidad de Concepción, Chile

**Diego Soler Tovar **| Universidad de la Salle, Bogotá, Colombia

**Hernando Uribe Castro** | Universidad Autónoma de Occidente, Cali, Colombia

**Jairo Andrés Valcárcel Torres** | I+R Consultores en Ingeniería y Riesgos. S.A.S, Bogotá, D.C, Colombia

**Francisco A. Velandia** | Escuela de Geología, Universidad Industrial de Santander, Bucaramanga, Colombia

