---
title-block-banner-color: "#151550ff"
---

# Lista de autores {.unnumbered}

**Leonardo Arias Bernal** **|** Facultad de Medicina Veterinaria, Facultad de Zootecnia, Fundación Universitaria Agraria de Colombia, Bogotá, Colombia

**Gabriel Bernal | **Departamento de Ingeniería Civil y Agrícola. Universidad Nacional de Colombia, Sede Bogotá, Colombia. INGENIAR Investigación y Consultoría en Ingeniería para Análisis del Riesgo, Bogotá, Colombia

**Omar Darío Cardona** **| **Instituto de Estudios Ambientales. Universidad Nacional de Colombia, Sede Manizales, Colombia. INGENIAR Investigación y Consultoría en Ingeniería para Análisis del Riesgo, Bogotá, Colombia

**Alba N. Castaño-Castaño** **| **Grupo de Investigación Georiesgos, Observatorio Sismológico y Geofísico del Suroccidente Colombiano (OSSO), Universidad del Valle, Ciudad Universitaria, Cali, Colombia

**Yeli C. Castillo-González** **| **Grupo de Investigación Georiesgos, Observatorio Sismológico y Geofísico del Suroccidente Colombiano (OSSO), Universidad del Valle, Ciudad Universitaria, Cali, Colombia

**Oswaldo Coca-Domínguez** **| **Programa de Geociencias Marinas y Costeras GEO. Instituto de Investigaciones Marinas y Costeras “José Benito Vives de Andréis” INVEMAR, Santa Marta, Colombia

**Yuli Corchuelo Cuervo** **| **Servicio Geológico Colombiano, Dirección de Geoamenazas, Grupo Investigaciones Geodésicas Espaciales, Bogotá, Colombia

**Fredy Díaz Mila** **| **Servicio Geológico Colombiano, Dirección de Geoamenazas, Grupo Investigaciones Geodésicas Espaciales, Bogotá, Colombia

**Jorge A. Díaz-Rentería** **| **Grupo de Investigación Georiesgos, Observatorio Sismológico y Geofísico del Suroccidente Colombiano (OSSO), Universidad del Valle, Ciudad Universitaria, Cali, Colombia

**Juan Echeverry | **Centro de Investigación en Materiales y Obras Civiles, Departamento de Ingeniería Civil y Ambiental, Universidad de los Andes, Bogotá, Colombia

**María Alejandra Escovar | **INGENIAR Investigación y Consultoría en Ingeniería para Análisis del Riesgo, Bogotá, Colombia

**Rafael Fernández | **Centro de Investigación en Materiales y Obras Civiles, Departamento de Ingeniería Civil y Ambiental, Universidad de los Andes, Bogotá, Colombia

**Rodrigo Forero Carrillo** **|** Facultad de Medicina Veterinaria, Facultad de Zootecnia, Fundación Universitaria Agraria de Colombia, Bogotá, Colombia

**Alejandro Franco Rojas** **| **Departamento de Ingeniería Civil, Universidad de La Salle, Bogotá, Colombia

**Gustavo Fuentes | **Centro de Investigación en Materiales y Obras Civiles, Departamento de Ingeniería Civil y Ambiental, Universidad de los Andes, Bogotá, Colombia

**William Oswaldo Gaviria Gutiérrez** **| **Programa de Psicología y Observatorio Psicosocial para la Gestión del Riesgo de Desastres. Universidad de Manizales, Manizales, Colombia

**Angie García | **Centro de Investigación en Materiales y Obras Civiles, Departamento de Ingeniería Civil y Ambiental, Universidad de los Andes, Bogotá, Colombia

**Nathalie García-Millán** **| **Grupo de Investigación Georiesgos, Observatorio Sismológico y Geofísico del Suroccidente Colombiano (OSSO), Universidad del Valle, Ciudad Universitaria, Cali, Colombia. Estudiante Doctorado Ciencias Ambientales, Universidad del Valle, Cali, Colombia

**Cesar Augusto Hidalgo M. |** Facultad de Ingeniería. Programa de Ingeniería Civil. Universidad de Medellín, Medellín, Colombia

**Leidy Giraldo Londoño** **| **Servicio Geológico Colombiano, Dirección de Geoamenazas, Grupo Investigaciones Geodésicas Espaciales, Bogotá, Colombia

**Nicolás Hernández Gallo** **| **Facultad de Medicina Veterinaria, 2Facultad de Zootecnia, Fundación Universitaria Agraria de Colombia, Bogotá, Colombia

**Diego Hernández Pulido** **| **Facultad de Medicina Veterinaria, Facultad de Zootecnia, Fundación Universitaria Agraria de Colombia, Bogotá, Colombia

**Daniela Jácome Hernández** **| **Departamento de Ingeniería Civil, Universidad de La Salle, Bogotá, Colombia

**Gonzalo Jiménez Alonso** **|** Facultad de Medicina Veterinaria, Facultad de Zootecnia, Fundación Universitaria Agraria de Colombia, Bogotá, Colombia

**Víctor Leonardo López Jiménez** **| **Ingeniería Ambiental y Sanitaria, Universidad de La Salle, Bogotá, Colombia

**Serguei Lonin** **| **Grupo de Investigación en Oceanología; Facultad de Oceanografía Física – Escuela Naval de Cadetes “Almirante Padilla”. Isla Naval Manzanillo, El Bosque, Cartagena de Indias, Colombia

**Julio Monroy** **| **Grupo de Investigación en Oceanología; Facultad de Oceanografía Física – Escuela Naval de Cadetes “Almirante Padilla”. Isla Naval Manzanillo, El Bosque, Cartagena de Indias, Colombia

**Héctor Mora-Páez** **| **Servicio Geológico Colombiano, Dirección de Geoamenazas, Grupo Investigaciones Geodésicas Espaciales, Bogotá, Colombia

**David Fernando Morales Giraldo** **| **Programa de Geociencias Marinas y Costeras GEO. Instituto de Investigaciones Marinas y Costeras “José Benito Vives de Andréis” INVEMAR, Santa Marta, Colombia

**Rafael Muñoz Quintero** **|** Departamento de Ingeniería Civil, Universidad de La Salle, Bogotá, Colombia

**Nelson Obregón Neira** **| **Instituto Geofísico, Pontificia Universidad Javeriana, Bogotá, Colombia

**Alexander Padilla González** **| **Departamento de Ingeniería Civil, Universidad de La Salle, Bogotá, Colombia

**Viviana Ramírez Loaiza** **| **Federación Luterana Mundial programa Colombia, Bogotá, Colombia

**Juan Carlos Reyes | **Centro de Investigación en Materiales y Obras Civiles, Departamento de Ingeniería Civil y Ambiental, Universidad de los Andes, Bogotá, Colombia

**Constanza Ricaurte-Villota** **| **Programa de Geociencias Marinas y Costeras GEO. Instituto de Investigaciones Marinas y Costeras “José Benito Vives de Andréis” INVEMAR, Santa Marta, Colombia 

**Julio Rubio | **Departamento de Geografía de la Universidad del Valle, Cali, Colombia. Universidad de San Buenaventura Cali, Colombia

**Takeshi Sagiya** **|** Centro de Investigación en Mitigación de Desastres, Universidad de Nagoya, Japón

**Elkin De J. Salcedo-Hurtado** **| **Grupo de Investigación Georiesgos, Observatorio Sismológico y Geofísico del Suroccidente Colombiano (OSSO), Universidad del Valle, Ciudad Universitaria, Cali, Colombia. Estudiante Doctorado Ciencias Ambientales, Universidad del Valle, Cali, Colombia. Universidad del Valle, Departamento de Geografía, Ciudad Universitaria, Cali, Colombia

**Karen A. Sánchez-Estupiñán** **| **Grupo de Investigación Georiesgos, Observatorio Sismológico y Geofísico del Suroccidente Colombiano (OSSO), Universidad del Valle, Ciudad Universitaria, Cali, Colombia 

**Javier Thomas | **Departamento de Geografía de la Universidad del Valle, Cali, Colombia

**Johnny Alexander Vega G. | **Facultad de Ingeniería. Programa de Ingeniería Civil. Universidad de Medellín, Medellín, Colombia

**Jorge A. Vélez-Correa** **| **Grupo de Investigación Georiesgos, Observatorio Sismológico y Geofísico del Suroccidente Colombiano (OSSO), Universidad del Valle, Ciudad Universitaria, Cali, Colombia. Estudiante Doctorado Ciencias Ambientales, Universidad del Valle, Cali, Colombia. Catedrático de la Maestría en Desarrollo Sustentable, Universidad del Valle, Cali, Colombia

**Paula Andrea Villegas González** **| **Instituto Geofísico, Pontificia Universidad Javeriana, Bogotá, Colombia

**Luis Yamin | **Centro de Investigación en Materiales y Obras Civiles, Departamento de Ingeniería Civil y Ambiental, Universidad de los Andes, Bogotá, Colombia

**Lina Andrea Zambrano Hernández** **|** Programa de Psicología y Observatorio Psicosocial para la Gestión del Riesgo de Desastres. Universidad de Manizales, Manizales, Colombia

**Nisley Zúñiga Estacio** **| **Grupo de Investigación Georiesgos, Observatorio Sismológico y Geofísico del Suroccidente Colombiano (OSSO), Universidad del Valle, Ciudad Universitaria, Cali, Colombia

**1**

