---
title-block-banner-color: "#151550ff"
---

# Página Legal {.unnumbered}

Iván Duque Márquez\
**Presidente de la República**

Eduardo José González Angulo\
**Director, Unidad Nacional para la Gestión del Riesgo de Desastres**

Gerardo Jaramillo Montenegro\
**Subdirector General, Unidad Nacional para la Gestión del Riesgo de Desastres**

Lina Dorado\
**Subdirectora para el Conocimiento del Riesgo, Unidad Nacional para la Gestión del Riesgo de Desastres**

Comisión Nacional Asesora para la Investigación en Gestión del Riesgo de Desastres (CNAIGRD)\
**Editores**\
&nbsp;&nbsp;Lina Dorado, Unidad Nacional para la Gestión del Riesgo de Desastres (UNGRD)\
&nbsp;&nbsp;Argiro Ramírez & Clara Beatriz Ocampo, Ministerio de Ciencia, Tecnología e Innovación (MINCIENCIAS)\
&nbsp;&nbsp;Omar Joaquín Agudelo, Centro de Estudios para la Prevención de Desastres (CEPREVE)\
&nbsp;&nbsp;Marta Calvache, Servicio Geológico Colombiano (SGC)\
&nbsp;&nbsp;Fabio Andrés Bernal, Instituto de Hidrología, Meteorología y Estudios Ambientales (IDEAM)\
&nbsp;&nbsp;Leonor Aydé Rodríguez, Instituto Geográfico Agustín Codazzi (IGAC)\
&nbsp;&nbsp;Wilson Ramírez & Dorotea Cardona, Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH)\
&nbsp;&nbsp;Capitán de Corbeta Cesar Grisales, Capitán Leonardo Marriaga & Diana Quintana, Dirección General Marítima (DIMAR)\
&nbsp;&nbsp;Alexander Figueroa & María Angélica Arenas, Ministerio de Ambiente y Desarrollo Sostenible (MINAMBIENTE)\
&nbsp;&nbsp;Carolina Queruz & Enrique Bolívar, Ministerio de Educación Nacional (MEN)\
&nbsp;&nbsp;Juan Pablo Londoño, Universidad de la Salle, representante universidades privadas\
&nbsp;&nbsp;Lina Ospina Ostios, Universidad del Valle, representante universidades públicas\
&nbsp;&nbsp;Carlos Arturo García. Red Universitaria de Las Américas y el Caribe para la Reducción del Riesgo de Desastres (REDULAC/RRD), Capítulo Colombia\
&nbsp;&nbsp;Cristian Jaimes, Instituto Distrital de Gestión de Riegos y Cambio Climático (IDIGER)

**Equipo técnico, Subdirección para el Conocimiento del Riesgo, UNGRD**\
Luisa Fernanda Cadena Amado\
Doralba Restrepo M.\
Mauricio Romero Torres

**Coordinación editorial**\
Mauricio Romero Torres

**Revisión de estilo**\
Kelly Barbosa

**Diseño y diagramación**\
Oficina de Comunicaciones: Jonathan Reyes\
Subdirección para el Conocimiento del Riesgo: Hugo Niño, Alejandro Herrera, Hugo Vanstralen y Diana Mancera

**Proceso de arbitraje**\
Revisión por pares doble ciega para cada capítulo

**ISBN obra digital**: 978-958-5509-19-1

Copyright: © Unidad Nacional para la Gestión del Riesgo de Desastres, abril de 2021\
Bogotá, Colombia

Todos los derechos reservados. Excepto si se señala otra cosa, la licencia del ítem se describe como Atribución NoComercial-SinDerivadas 2.5 Colombia

Distribución gratuita – versión digital
